<div class="row">
	
	<div class="limiter">
		<h2>Reporte de Ventas</h2>
		<br>
		<div class="table100 ver2 m-b-110">
			<table data-vertable="ver2" >
				<thead >
					<tr class="row100 head">
						<th class="column100 column1" data-column="column1">Fecha</th>
						<th class="column100 column2" data-column="column2">Serie</th>
						<th class="column100 column3" data-column="column3">Numero</th>
						<th class="column100 column4" data-column="column4">Total Factura</th>
						<th class="column100 column5" data-column="column5">Total Ventas</th>
					</tr>
				</thead>
				<tbody id="ventas">					
				</tbody>
			</table>
		</div>
	</div>

	<div class="limiter">
		<h2>Reporte de Movimientos</h2>
		<br>
		<div class="table100 ver2 m-b-110">
			<table data-vertable="ver2" >
				<thead >
					<tr class="row100 head">
						<th class="column100 column1" data-column="column1">Movimiento</th>
						<th class="column100 column2" data-column="column2">Sucursal</th>
						<th class="column100 column3" data-column="column3">Documento</th>
						<th class="column100 column4" data-column="column4">Operación</th>
						<th class="column100 column5" data-column="column5">Fecha</th>
						<th class="column100 column6" data-column="column6">Serie</th>
						<th class="column100 column7" data-column="column7">Numero</th>
						<th class="column100 column8" data-column="column8">Total</th>
						<th class="column100 column9" data-column="column9">Proveedor</th>
						<th class="column100 column10" data-column="column10">Operador</th>
					</tr>
				</thead>
				<tbody id="movimientos">
				</tbody>
			</table>
		</div>
	</div>

	<div class="limiter">
		<h2>Reporte de Inventario</h2>
		<br>
		<div class="table100 ver2 m-b-110">
			<table data-vertable="ver2">
				<thead >
					<tr class="row100 head">
						<th class="column100 column1" data-column="column1">ID</th>
						<th class="column100 column2" data-column="column2">Código de Barras</th>
						<th class="column100 column3" data-column="column3">Descripcion</th>
						<th class="column100 column4" data-column="column4">Marca</th>
						<th class="column100 column5" data-column="column5">Modelo</th>
						<th class="column100 column6" data-column="column6">Tipo Producto</th>
						<th class="column100 column7" data-column="column7">Estado Producto</th>
						<th class="column100 column8" data-column="column8">Precio</th>
						<th class="column100 column9" data-column="column9">Existencia</th>
						<th class="column100 column10" data-column="column10">Valor</th>
						<th class="column100 column11" data-column="column11">Patrimonio</th>
					</tr>
				</thead>
				<tbody id="inventario">
				</tbody>
			</table>
		</div>
	</div>


</div>
