<div class="widget widget-table">
	<div class="widget-header">
		<h3><i class="fa fa-edit"></i> Mantenimiento de Informaci&oacute;n</h3> <em>- Ingresar, Consultar, actualizar y eliminar informaci&oacute;n</em>
		<button type="button" id="<?php echo $this->boton_ayuda ?>" class="btn btn-link btn-help"><i class="fa fa-question-circle"></i></button>
		<div class="btn-group widget-header-toolbar">
			<button id="enable" class="btn btn-default btn-sm">Enable / Disable</button>
		</div>		
		<div class="btn-group widget-header-toolbar">
			<div class="control-inline toolbar-item-group">
				<span class="control-title">Edición en Línea</span>
				<div class="control-inline onoffswitch">
					<input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="switch-inline-input">
					<label class="onoffswitch-label" for="switch-inline-input">
						<span class="onoffswitch-inner"></span>
						<span class="onoffswitch-switch"></span>
					</label>
				</div>
			</div>	
		</div>
		<div class="btn-group widget-header-toolbar">
			<a href="#" title="Focus" class="btn-borderless btn-focus"><i class="fa fa-eye"></i></a>
			<a href="#" title="Expand/Collapse" class="btn-borderless btn-toggle-expand"><i class="fa fa-chevron-up"></i></a>
			<a href="#" title="Remove" class="btn-borderless btn-remove"><i class="fa fa-times"></i></a>
		</div>
	</div>
	<div class="widget-content">
<ul class="nav nav-tabs nav-tabs-custom-colored tabs-iconized">
	<li class="active"><a href="#profile-tab" data-toggle="tab"><i class="fa fa-user"></i> Perfil de Usuario</a></li>
	<li><a href="#settings-tab" data-toggle="tab"><i class="fa fa-gear"></i> Configuración</a></li>
</ul>
<div class="tab-content profile-page">
	<div class="tab-pane profile active" id="profile-tab">
		<div class="row">
			<div class="col-md-3">
				<div class="user-info-left">
					<img id="avatar_perfil" src="<?php echo PERFIL_USUARIO.'img/'.$this->usuario['avatar'];?>" alt="Foto de Perfil" class="img-responsive" />
					<h2><?php echo $this->usuario['descripcion'];?> <i class="fa fa-circle green-font online-icon"></i><sup class="sr-only">online</sup></h2>
					<div id="kv-avatar-errors-2" class="center-block" style="width:800px;display:none"></div>
				</div>
			</div>
			<div class="col-md-9">
				<div class="user-info-right">
					<div id="user" class="basic-info">
						<h3><i class="fa fa-square"></i> Información General</h3>
						<p class="data-row">
							<span class="data-name">ID Usuario</span>
							<span class="data-value"><?php echo $this->usuario['id_entidad'];?></span>
							<input type="hidden" id="id_entidad" value="<?php echo $this->usuario['id_entidad'];?>"/>
						</p>						
						<p class="data-row">
							<span class="data-name">Usuario</span>
							<span class="data-value"><a href="#" id="usuario" data-type="text" data-pk="<?php echo $this->usuario['id_entidad'];?>" data-title="Ingrese su Usuario:"><?php echo $this->usuario['usuario'];?></a></span>
						</p>
						<p class="data-row">
							<span class="data-name">Correo Electrónico</span>
							<span class="data-value"><a href="#" id="correo" data-type="email" data-pk="<?php echo $this->usuario['id_entidad'];?>" data-title="Ingrese su Correo Electrónico"><?php echo $this->usuario['correo'];?></a></span>
						</p>
						<p class="data-row">
							<span class="data-name">Teléfono</span>
							<span class="data-value"><a href="#" id="telefono" data-type="text" data-pk="<?php echo $this->usuario['id_entidad'];?>" data-title="Ingrese su Teléfono:"><?php echo $this->usuario['telefono'];?></a></span>
						</p>
						<p class="data-row">
							<span class="data-name">Celular</span>
							<span class="data-value"><a href="#" id="celular" data-type="text" data-pk="<?php echo $this->usuario['id_entidad'];?>" data-title="Ingrese su Celular:"><?php echo $this->usuario['celular'];?></a></span>
						</p>
						<p class="data-row">
							<span class="data-name">Estado</span>
							<span class="data-value"><?php if($this->usuario['estado_registro']=='A'){echo 'Alta';}else{echo 'Baja';};?></span>
							<!--<span class="data-value"><a href="#" id="estado_registro" data-type="select" data-pk="<?php echo $this->usuario['id_entidad'];?>" data-title="Elija su Estado:" ></a></span>-->
							<!--<input type="hidden" id="estado_registro1" value="<?php echo $this->usuario['estado_registro'];?>"/>-->
						</p>
						<h3><i class="fa fa-square"></i> Avatar</h3>
						<div class="row">
							<div class="col-md-4">
		 						<div class="kv-avatar">
		               		<div class="file-loading">
		                    		<input id="avatar-1" name="avatar-1" type="file" required>
		                		</div>
		            		</div>						
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="tab-pane settings" id="settings-tab">
		<form id="frmCambioClave" class="form-horizontal" role="form">
			<fieldset>
				<h3><i class="fa fa-square"></i> Cambiar Clave de Acceso</h3>
				<div class="form-group">
					<label for="old-password" class="col-sm-3 control-label">Clave de Acceso Anterior</label>
					<div class="col-sm-4">
						<input type="password" id="old_password" name="old_password" class="form-control" placeholder="Ingrese su clave de acceso actual" >
					</div>
				</div>
				<hr />
				<div class="form-group">
					<label for="password" class="col-sm-3 control-label">Nueva Clave de Acceso</label>
					<div class="col-sm-4">
						<input type="password" id="password1" name="password1" class="form-control" placeholder="Ingrese su nueva clave de acceso" >
						<div class="progress progress-xs" style="margin: 1px;">
							<div id="pass1" class="progress-bar" data-transitiongoal="1"></div>
						</div>
						<span id="result1"></span>
					</div>
					
				</div>
				<div class="form-group">
					<label for="password2" class="col-sm-3 control-label">Confirmar Clave de Acceso</label>
					<div class="col-sm-4">
						<input type="password" id="password2" name="password2" class="form-control" placeholder="Confirme su nueva clave de acceso" >
						<span id="result2"></span>
					</div>
				</div>
			</fieldset>
		</form>
		<div class="col-sm-4 col-sm-offset-3">
		<p class="text-right"><a href="#" id="aceptar" class="btn btn-custom-primary"><i class="fa fa-floppy-o"></i> Aceptar</a></p>
		</div>
	</div>
</div>
	</div>
</div>