<div class="widget widget-table">
	<div class="widget-header">
		<h3><i class="fa fa-table"></i> Mantenimiento de Informaci&oacute;n</h3> <em>- Ingresar, Consultar, actualizar y eliminar informaci&oacute;n</em>
		<button type="button" id="<?php echo $this->boton_ayuda ?>" class="btn btn-link btn-help"><i class="fa fa-question-circle"></i></button>
		<div class="btn-group widget-header-toolbar">
			<a href="#" title="Focus" class="btn-borderless btn-focus"><i class="fa fa-eye"></i></a>
			<a href="#" title="Expand/Collapse" class="btn-borderless btn-toggle-expand"><i class="fa fa-chevron-up"></i></a>
			<a href="#" title="Remove" class="btn-borderless btn-remove"><i class="fa fa-times"></i></a>
		</div>
	</div>
	<div class="widget-content">
 		<div class="col-md-12 col-sm-12 col-xs-12">
 			<form id="frmRolEntidad">
 				<div class="row">
					<div class="form-group">
						<label>Grupo de Usuarios:</label>
						<div class="input-group">
    		  				<?php echo $this->grupo; ?>
    		  				<span class="input-group-addon"><i class="fa fa-user"></i></span>
    		  			</div>
					</div>    		
 				</div>
 				<div class="row">
 					<?php echo $this->menu; ?>
				</div> 
				<div class="row">
					<div class="form-group">
						<div class="input-group">
							<br />
 							<input type="button" id="aceptar" value="Aceptar" class="btn btn-default"/>
 						</div>
 					</div>
				</div> 					
				
 			</form>
		</div>
		
  	</div>
</div>


<style>
	.widget-content {
		overflow-x: hidden;
	}
	.move {
		height: 34px;
	}
	.remove {
		height: 34px;
	}
</style>