<div class="widget widget-table">
	<div class="widget-header">
		<h3><i class="fa fa-table"></i> Mantenimiento de Informaci&oacute;n</h3> <em>- Ingresar informaci&oacute;n</em>
		<button type="button" id="<?php echo $this->boton_ayuda ?>" class="btn btn-link btn-help"><i class="fa fa-question-circle"></i></button>
		<div class="btn-group widget-header-toolbar">
			<a href="#" title="Focus" class="btn-borderless btn-focus"><i class="fa fa-eye"></i></a>
			<a href="#" title="Expand/Collapse" class="btn-borderless btn-toggle-expand"><i class="fa fa-chevron-up"></i></a>
			<a href="#" title="Remove" class="btn-borderless btn-remove"><i class="fa fa-times"></i></a>
		</div>
	</div>
	<div class="widget-content">
		<form role="form" id="frmEncabezado">
			<input type="hidden" id='operacion' name='operacion' value="add" />
			<div class="row">
		   		<div class="col-xs-12 col-md-3">
					<div class="form-group">
						<label>Clave:</label>
						<div class="input-group">
							<input type='text' id='clave' name='clave' class="form-control" placeholder="Clave para la Receta" maxlength="15" required="true" />
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>				
			</div>
			<div class="row">
				<div class="col-xs-12 col-md-6">
					<div class="form-group">
						<label>Nombre de la Receta:</label>
						<div class="input-group">
							<input type='text' id='descripcion' name='descripcion' class="form-control" placeholder="Escriba el nombre de la receta" maxlength="50" required="true" />
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>	
				<div class="col-xs-12 col-md-6">
					<div class="form-group">
						<label>Observaciones</label>
						<div class="input-group">
							<input type='text' id='observaciones' name='observaciones' class="form-control" placeholder="Observaciones" maxlength="25" />
							<span class="input-group-addon"><i class="far fa-comment"></i></span>
						</div>
					</div>
				</div>										
											
			</div>			
			<div class="row">
				<div class="col-xs-12 col-md-6">
					<div class="form-group">
						<button id='aceptar_encabezado' type="button" class="btn btn-primary ">Ingresar Encabezado</button>
					</div>
				</div>
			</div>
		</form>
		<form role="form" id="frmDetalle">
			<div class="row">
				<div class="col-xs-12 col-md-12">				
					<div class="row">
						<div class="col-xs-12 col-md-10">
							<h3>Detalle de la receta</h3>
						</div>
						<div class="col-xs-12 col-md-2">
							<h2 id="correlativo"></h2>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-md-4">
					<div class="form-group">
						<label>Producto:</label>
						<div class="input-group">
	    		  			<?php echo $this->producto; ?>
	    		  			<span class="input-group-addon"><i class="fas fa-box"></i></span>
	    		  		</div>
					</div>
				</div><div class="col-xs-12 col-md-8">
					<div class="form-group">
						<label>Descripción:</label>
						<div class="input-group">
							<input type='text' id='descripcion' name='descripcion' class="form-control" placeholder="Descipción" maxlength="25" required="true"  />
							<span class="input-group-addon"><i class="fas fa-boxes"></i></span>
	    		  		</div>
					</div>
				</div>
				<div class="col-xs-12 col-md-4">
					<div class="form-group">
						<label>Cantidad:</label>
						<div class="input-group">
							<input type='text' id='cantidad' name='cantidad' class="form-control" placeholder="Cantidad" maxlength="25" required="true"  />
							<span class="input-group-addon"><i class="fas fa-boxes"></i></span>
	    		  		</div>
					</div>
				</div>
				<div class="col-xs-12 col-md-4">
					<div class="form-group">
						<label>Medida:</label>
						<div class="input-group">
							 <?php echo $this->medida?>
							<span class="input-group-addon"><i class="fab fa-acquisitions-incorporated"></i></span>
	    		  		</div>
					</div>
				</div>
			</div>
			<div class="row ">
				<div class="col-xs-12 col-md-6">
					<div class="form-group">
						<button id='agregar_producto' type="button" class="btn btn-primary ">Ingresar producto</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-md-12">
					<div id="jqgrid-wrapper">
						<table id="jqgrid1" class="table table-striped table-hover"></table>
						<div id="jqgrid-pager1"></div>
					</div>
					<br />	
				</div>
			</div>	
		</form>	
		<div class="row ">
			<div class="col-xs-12 col-md-6">
				<div class="form-group">
					<button id='aceptar_detalle' type="button" class="btn btn-success ">Ingresar detalle</button>
				</div>
			</div>
		</div>				
	</div>
	
</div>
