<div class="widget widget-table">
	<div class="widget-header">
		<h3><i class="fa fa-table"></i> Mantenimiento de Informaci&oacute;n</h3> <em>- Ingresar informaci&oacute;n</em>
		<button type="button" id="<?php echo $this->boton_ayuda ?>" class="btn btn-link btn-help"><i class="fa fa-question-circle"></i></button>
		<div class="btn-group widget-header-toolbar">
			<a href="#" title="Focus" class="btn-borderless btn-focus"><i class="fa fa-eye"></i></a>
			<a href="#" title="Expand/Collapse" class="btn-borderless btn-toggle-expand"><i class="fa fa-chevron-up"></i></a>
			<a href="#" title="Remove" class="btn-borderless btn-remove"><i class="fa fa-times"></i></a>
		</div>
	</div>
	<div class="widget-content">
<form role="form" id="frmEncabezado">
			<input type="hidden" id='operacion' name='operacion' value="add" />
			<div class="row">
		   		<div class="col-xs-12 col-md-4">
					<div class="form-group">	 
						<label for="booking">Tipo de Documento:</label>
						<div class="input-group"> 
							<?php echo $this->tipo_documento; ?>
							<span class="input-group-addon"><i class="fa fa-edit"></i></span>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-md-3">
					<div class="form-group">
						<label>Fecha:</label>
						<div class="input-group">
							<input type='text' id='fecha' name='fecha' class="form-control" placeholder="Fecha Documento" maxlength="15" required="true" />
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>	
				<div class="col-xs-12 col-md-2">
					<div class="form-group">
						<label>Serie</label>
						<div class="input-group">
							<input type='text' id='serie' name='serie' class="form-control" placeholder="Serie" maxlength="25" required="true"  />
							<span class="input-group-addon"><i class="fa fa-clipboard"></i></span>
						</div>
					</div>
				</div>										
				<div class="col-xs-12 col-md-3">
					<div class="form-group">
						<label>Numero</label>
						<div class="input-group">
							<input type='text' id='numero' name='numero' class="form-control" placeholder="Número" maxlength="25" required="true"  />
							<span class="input-group-addon"><i class="fa fa-hashtag"></i></span>
						</div>
					</div>
				</div>			
			</div>
			<div class="row">
				 <div class="form-group">
				   <div class="col-xs-12 col-md-8">
					   <label for="observaciones">Observaciones</label>
					       <textarea name="observaciones" id="observaciones" class="form-control" rows="3" placeholder="Observaciones de la devolución"></textarea>
				   </div>
				 </div>
			</div>	
			<div class="row">
				<div class="col-xs-12 col-md-12">
					<hr>
				</div>
			</div>
		</form>
		<form role="form" id="frmDetalle">
			<div class="row">
				<div class="col-xs-12 col-md-12">				
					<div class="row">
						<div class="col-xs-12 col-md-10">
							<h3>Detalle del Egreso</h3>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-md-4">
					<div class="form-group">
						<label>Bodega de Ingreso:</label>
						<div class="input-group">
	    		  			<?php echo $this->bodega; ?>
	    		  			<span class="input-group-addon"><i class="fa fa-home"></i></span>
	    		  		</div>
					</div>
				</div>
				<div class="col-xs-12 col-md-4">
					<div class="form-group">
						<label>Producto:</label>
						<div class="input-group">
	    		  			<?php echo $this->producto; ?>
	    		  			<span class="input-group-addon"><i class="fas fa-box"></i></span>
	    		  		</div>
					</div>
				</div>
				<div class="col-xs-12 col-md-4">
					<div class="form-group">
						<label>Unidades:</label>
						<div class="input-group">
							<input type='text' id='unidades' name='unidades' class="form-control" placeholder="Unidades" maxlength="25" required="true"  />
							<span class="input-group-addon"><i class="fas fa-boxes"></i></span>
	    		  		</div>
					</div>
				</div>
			</div>
			<div class="row ">
				<div class="col-xs-12 col-md-6">
					<div class="form-group">
						<button id='agregar_producto' type="button" class="btn btn-primary ">Ingresar producto</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-md-12">
					<div id="jqgrid-wrapper">
						<table id="jqgrid1" class="table table-striped table-hover"></table>
						<div id="jqgrid-pager1"></div>
					</div>
					<br />	
				</div>
			</div>	
		</form>	
		<div class="row ">
			<div class="col-xs-12 col-md-6">
				<div class="form-group">
					<button id='aceptar' type="button" class="btn btn-success ">Registrar Egreso</button>
				</div>
			</div>
		</div>				
	</div>
	
</div>
